set_property IOSTANDARD LVCMOS33 [get_ports rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_0]
set_property PACKAGE_PIN R12 [get_ports tx_0]
set_property PACKAGE_PIN V12 [get_ports rx_0]
set_property PACKAGE_PIN K9 [get_ports Vp_Vn_0_v_n]
